#! /bin/sh
### BEGIN INIT INFO
# Provides:          sslocald
# Required-Start:    $local_fs $network $remote_fs network-manager
# Required-Stop:     $local_fs $network $remote_fs
# Should-Start:      $NetworkManager
# Should-Stop:       $NetworkManager
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of sslocal
# Description:       starts instance of sslocal using start-stop-daemon
### END INIT INFO

# https://debian-administration.org/article/28/Making_scripts_run_at_boot_time_with_Debian
# https://github.com/Sonarr/Sonarr/wiki/Autostart-on-Debian
# https://github.com/shadowsocks/shadowsocks/wiki/Configuration-via-Config-File
CONFIGURATION=/etc/shadowsocks.json

case "$1" in
  start)
    echo "Starting shadowsocks "
    sslocal -c $CONFIGURATION -d start
    ;;
  restart)
    echo "Restarting shadowsocks"
    sslocal -c $CONFIGURATION -d restart
    ;;
  stop)
    echo "Stopping shadowsocks"
    sslocal -c $CONFIGURATION -d stop
    ;;
  *)
    echo "Usage: /etc/init.d/sslocald {start|restart|stop}"
    exit 1
    ;;
esac

exit 0
